apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-external-secret
spec:
  secretStoreRef:
    name: mysecretstore
    kind: SecretStore
  target:
    name: aws-secret
  data:
    - secretKey: secret-key
      remoteRef:
        key: myawssecret # AWS SM secret name or ID
        property: key
